services:
  backend:
    build:
      context: ./Proinvest-BACK
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./Proinvest-FRONT/parcela-app
    ports:
      - "5173:80"
    depends_on:
      - backend
